// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ringolingo.Data;

#nullable disable

namespace Ringolingo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314141351_SessaoAndHistorico")]
    partial class SessaoAndHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ringolingo.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("xpGanhado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Envie 100 mensagens com qualquer um dos ringos",
                            Titulo = "Mensageiro",
                            xpGanhado = 200
                        });
                });

            modelBuilder.Entity("Ringolingo.Models.ConquistaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConquistaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConquistaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conquistaUsuarios");
                });

            modelBuilder.Entity("Ringolingo.Models.HistoricoXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoXps");
                });

            modelBuilder.Entity("Ringolingo.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnviadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SessaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Ringolingo.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeNecessaria")
                        .HasColumnType("int");

                    b.Property<int>("XpRecompensa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("missaos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Envie 5 mensagens para qualquer ringo",
                            Emoji = "💬",
                            Nome = "Conversador",
                            QuantidadeNecessaria = 0,
                            XpRecompensa = 30
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Envie 10 mensagens para qualquer ringo",
                            Emoji = "🗣️",
                            Nome = "Tagarela",
                            QuantidadeNecessaria = 0,
                            XpRecompensa = 50
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Converse com pelo menos 2 Ringos diferentes",
                            Emoji = "🌍",
                            Nome = "Explorador",
                            QuantidadeNecessaria = 0,
                            XpRecompensa = 25
                        });
                });

            modelBuilder.Entity("Ringolingo.Models.MissaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissaoId")
                        .HasColumnType("int");

                    b.Property<int>("Progresso")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("missaoUsuarios");
                });

            modelBuilder.Entity("Ringolingo.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelNecessario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Descricao = "You are Ringo, an English teacher acting as the user's best friend. Your answers must ALWAYS follow this exact format, with the labels included:English:<Write the dialogue in casual, friendly English with slang and everyday expressions here>Portuguese:<Write the same dialogue translated into Portuguese here>Teacher's Tip (English):<Write a short teaching tip in English about informal language, slang, or natural conversation here>Dica do Professor (Português):<Write the same teaching tip translated into Portuguese here>Important rules:- Do not add slashes, asterisks, or extra symbols.- Do not mix English and Portuguese in the same section.- Always keep the labels exactly as shown.- Always use line breaks between sections.",
                            ImagemUrl = "/personas/ringoBestFriend.png",
                            NivelNecessario = 0,
                            Nome = "BestFriend"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "You are Ringo, an English teacher acting as a polite waiter. Your answers must ALWAYS follow this exact format, with the labels included:English:<Write the dialogue in English using restaurant and service vocabulary here>Portuguese:<Write the same dialogue translated into Portuguese here>Teacher's Tip (English)<Write a short teaching tip in English about vocabulary, grammar, or expressions used in restaurant situations here>Dica do Professor (Português):<Write the same teaching tip translated into Portuguese here>Important rules:- Do not add slashes, asterisks, or extra symbols.- Do not mix English and Portuguese in the same section.- Always keep the labels exactly as shown.- Always use line breaks between sections.",
                            ImagemUrl = "/personas/ringoGarçom.png",
                            NivelNecessario = 5,
                            Nome = "Garçom"
                        },
                        new
                        {
                            Id = 1,
                            Descricao = "You are Ringo, an English teacher acting as a professional interviewer.  Your answers must ALWAYS follow this exact format, with the labels included:  English: <Write the dialogue in formal, professional English here>  Portuguese: <Write the same dialogue translated into Portuguese here>  Teacher's Tip (English): <Write a short teaching tip in English here>  Dica do Professor (Português): <Write the same teaching tip translated into Portuguese here>  Important rules: - Do not add slashes, asterisks, or extra symbols. - Do not mix English and Portuguese in the same section. - Always keep the labels exactly as shown. - Always use line breaks between sections.",
                            ImagemUrl = "/personas/ringoEntrevistador.png",
                            NivelNecessario = 10,
                            Nome = "Entrevistador"
                        });
                });

            modelBuilder.Entity("Ringolingo.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sessaos");
                });

            modelBuilder.Entity("Ringolingo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SupabaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("XpDoNivel")
                        .HasColumnType("int");

                    b.Property<int>("XpTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ringolingo.Models.ConquistaUsuario", b =>
                {
                    b.HasOne("Ringolingo.Models.Conquista", "Conquista")
                        .WithMany("UsuarioConquista")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ringolingo.Models.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ringolingo.Models.HistoricoXp", b =>
                {
                    b.HasOne("Ringolingo.Models.Usuario", "Usuario")
                        .WithMany("HistoricoXp")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ringolingo.Models.Mensagem", b =>
                {
                    b.HasOne("Ringolingo.Models.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ringolingo.Models.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Ringolingo.Models.Sessao", b =>
                {
                    b.HasOne("Ringolingo.Models.Usuario", null)
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ringolingo.Models.Conquista", b =>
                {
                    b.Navigation("UsuarioConquista");
                });

            modelBuilder.Entity("Ringolingo.Models.Usuario", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("HistoricoXp");

                    b.Navigation("Mensagens");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
