// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbSSuddlpBfBGwbaPrHqWvryNHWOYJHl8',
    appId: '1:578727182197:web:963c0f1e09363dfd309d3c',
    messagingSenderId: '578727182197',
    projectId: 'ringolingo-437bb',
    authDomain: 'ringolingo-437bb.firebaseapp.com',
    storageBucket: 'ringolingo-437bb.firebasestorage.app',
    measurementId: 'G-XD2LXJN5V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIugBBexJpZJqwdgKJzy407oUYaZroTs',
    appId: '1:578727182197:android:d7c06b2b3f96090b309d3c',
    messagingSenderId: '578727182197',
    projectId: 'ringolingo-437bb',
    storageBucket: 'ringolingo-437bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtuCFcmUt-41J47DmwqXHcJqf7WCzV8a0',
    appId: '1:578727182197:ios:a3fab524bdf7a0f5309d3c',
    messagingSenderId: '578727182197',
    projectId: 'ringolingo-437bb',
    storageBucket: 'ringolingo-437bb.firebasestorage.app',
    iosBundleId: 'com.example.ringolingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuCFcmUt-41J47DmwqXHcJqf7WCzV8a0',
    appId: '1:578727182197:ios:a3fab524bdf7a0f5309d3c',
    messagingSenderId: '578727182197',
    projectId: 'ringolingo-437bb',
    storageBucket: 'ringolingo-437bb.firebasestorage.app',
    iosBundleId: 'com.example.ringolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbSSuddlpBfBGwbaPrHqWvryNHWOYJHl8',
    appId: '1:578727182197:web:cbe6f7f047fc6008309d3c',
    messagingSenderId: '578727182197',
    projectId: 'ringolingo-437bb',
    authDomain: 'ringolingo-437bb.firebaseapp.com',
    storageBucket: 'ringolingo-437bb.firebasestorage.app',
    measurementId: 'G-50TKQNWZM3',
  );
}
